# Exported from Render on 2024-09-14T12:21:59Z
databases:
- name: ffchubDatabase
  databaseName: ffcdb
  user: ffchub
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
