# Generated by Django 5.1.1 on 2024-09-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_challenge_leaderboardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessactivity',
            name='tss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
