# Generated by Django 5.1.1 on 2024-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_invitation_challenge_invitation_invitation_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='receiver',
            new_name='invitee',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invitation_type',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='status',
        ),
        migrations.AddField(
            model_name='invitation',
            name='invite_type',
            field=models.CharField(choices=[('group', 'Group'), ('challenge', 'Challenge')], default='GROUP', max_length=10),
        ),
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
