# Generated by Django 5.1.1 on 2024-09-09 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_challenge_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='FitnessGroup',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='group',
            new_name='fitness_group',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='group',
            new_name='fitness_group',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invite_type',
            field=models.CharField(choices=[('fitnessGroup', 'FitnessGroup'), ('challenge', 'Challenge')], default='FitnessGroup', max_length=20),
        ),
    ]
