# Generated by Django 5.1.1 on 2024-12-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0009_rename_group_fitnessgroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("CAL", "Calories"),
                    ("KM", "Kilometers"),
                    ("TSS", "TSS"),
                    ("Fastest Run", "Time"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="fitnessactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("RUN", "Running"),
                    ("YOG", "Yoga"),
                    ("CYC", "Cycling"),
                    ("WEI", "Wheight Lift"),
                ],
                max_length=3,
            ),
        ),
    ]
