# Generated by Django 5.1.1 on 2024-12-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0010_alter_challenge_challenge_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fitnessgroup",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
