# Generated by Django 5.1.1 on 2024-12-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0012_invitation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="fitnessactivity",
            name="duration",
            field=models.IntegerField(),
        ),
    ]
