# Generated by Django 5.1.1 on 2024-12-18 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0013_challenge_description_alter_fitnessactivity_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessactivity",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fitnessgroup",
            name="admins",
            field=models.ManyToManyField(
                related_name="admin_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
