# Generated by Django 5.1.1 on 2024-12-19 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0014_fitnessactivity_distance_fitnessgroup_admins"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitnessactivity",
            name="intensity",
        ),
        migrations.AddField(
            model_name="fitnessactivity",
            name="perceived_effort",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="fitnessactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("RUN", "Running"),
                    ("YOG", "Yoga"),
                    ("CYC", "Cycling"),
                    ("STR", "Strength"),
                    ("WAL", "Walk"),
                    ("IBK", "Indoor Bike"),
                    ("TRE", "Treadmill"),
                    ("CAR", "Cardio Trainning"),
                    ("CAR", "Cardio Trainning"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="fitnessactivity",
            name="duration",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(1440)]
            ),
        ),
    ]
