# Generated by Django 5.1.1 on 2024-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0017_alter_fitnessactivity_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessactivity",
            name="calories_burned",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
